name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release Version e.g.: 1.0'
        required: true

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW32

      - name: Install MinGW
        run: |
          pacman --noconfirm -S mingw-w64-i686-gcc

      - uses: actions/checkout@v4

      - name: Build Patcher
        run: ./make.bat

      - name: Create Pre Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: v${{ github.event.inputs.version }}
        shell: bash
        run: gh release create "$TAG" -p --generate-notes FaP.exe
